import { TileType } from './TileGrid';

/** Column order of tiles baked into the single "tileset" texture strip
 * generated by PixelArtFactory. Both sides must agree on this order. */
export const TILE_ORDER: TileType[] = [
  TileType.GRASS,
  TileType.PARK,
  TileType.ROAD,
  TileType.PLAZA,
  TileType.PATH,
  TileType.RAIL,
  TileType.WATER,
];

const indexByType = new Map<TileType, number>(TILE_ORDER.map((t, i) => [t, i]));

export function tileTypeToIndex(type: TileType): number {
  return indexByType.get(type) ?? 0;
}

export const TILESET_KEY = 'tileset';
