/**
 * AUTO-GENERATED by scripts/generate-city-data.mjs — tile-space anchor
 * points for the curated real landmarks referenced from src/data/landmarks.ts.
 * Re-run the generator to refresh; do not hand-edit.
 */
export interface LandmarkAnchor {
  tileX: number;
  tileY: number;
  buildingId?: string;
}

export const landmarkAnchors: Record<string, LandmarkAnchor> = {
  andrassy_manor: { tileX: 240.95, tileY: 431.38, buildingId: "andrassy_manor" },
  mestsky_park: { tileX: 227.64, tileY: 364.55 },
  koniaren_gallery: { tileX: 254.73, tileY: 446.39, buildingId: "koniaren_gallery" },
  parish_church: { tileX: 236.74, tileY: 360.14, buildingId: "parish_church" },
  greekcatholic_church: { tileX: 234.09, tileY: 331.12, buildingId: "greekcatholic_church" },
  town_hall: { tileX: 204.58, tileY: 450.01, buildingId: "town_hall" },
  culture_centre: { tileX: 234.62, tileY: 315.63, buildingId: "culture_centre" },
  andrassy_mausoleum: { tileX: 346.91, tileY: 363.40, buildingId: "andrassy_mausoleum" },
  paric_castle: { tileX: 353.29, tileY: 403.14, buildingId: "paric_castle" },
  train_station: { tileX: 93.67, tileY: 54.11, buildingId: "train_station" },
};
